start_nest:
  defaultBuilder:
    languages:
      - nodejs20
    steps:
      - run: PATH=/usr/local/versions/node/v20.8.1/bin:$PATH && npm install
        path: ./code
      - run: PATH=/usr/local/versions/node/v20.8.1/bin:$PATH && npm run build
        path: ./code