start_next:
  defaultBuilder:
    languages:
      - nodejs20
    steps:
      - run: PATH=/usr/local/versions/node/v20.8.1/bin:$PATH && npm install
        path: ./code
      - run: PATH=/usr/local/versions/node/v20.8.1/bin:$PATH && npm run build
        path: ./code
      - run: cp -r public .next/standalone/public
        path: ./code
      - run: cp -r static standalone/.next/static
        path: ./code/.next